### ISSUE TITLE
Practica #1- FRONT-END

### ISSUE THREAD

**Issue by Anna-Aparicio** [SistemasTecTlaxiaco/practica-de-mockup-y-front-end-cb-24h#2]
[Practica 1_ Front-End.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-mockup-y-front-end-cb-24h/files/6549425/Practica.1_.Front-End.pdf)

**Comment by Anthony4523** [comment]
Buen trabajo

Calificación: 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
